[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for functions
[build.environment]
  NODE_VERSION = "18"

# Keep-alive function settings
[[functions]]
  path = "/.netlify/functions/keep-alive"
  included_files = ["netlify/functions/keep-alive.js"]